# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Oct 17 15:08:41 2025
# ------------------------------------------------

package:
  name: micromamba
  version: 2.3.3
source:
  - url: https://github.com/mamba-org/mamba/archive/refs/tags/2.3.3.tar.gz
    sha256: 4f1aaf3aa5098037c3fc1571feaa2d8f256829baafd6d5b4556624791e5c0217
    folder: mamba
build:
  number: '0'
  string: '0'
  ignore_run_exports_from:
    - fmt
    - gcc_linux-64 14.*
    - gxx_linux-64 14.*
    - libarchive-minimal-static
    - libcurl
    - libsolv
    - openssl
    - spdlog
    - zlib
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 hdf8817f_2
    - binutils_linux-64 2.44 h4852527_2
    - bzip2 1.0.8 hda65f42_8
    - c-ares 1.34.5 hb9d3cd8_0
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - cmake 3.31.8 hc85cc9f_0
    - gcc_impl_linux-64 14.3.0 hd9e9e21_7
    - gcc_linux-64 14.3.0 h298d278_12
    - gxx_impl_linux-64 14.3.0 he663afc_7
    - gxx_linux-64 14.3.0 h95f728e_12
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.3 hb9d3cd8_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libcurl 8.14.1 h332b0f4_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.7.1 hecca717_0
    - libgcc 15.2.0 h767d61c_7
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_107
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - liblzma 5.8.1 hb9d3cd8_2
    - libnghttp2 1.67.0 had1ee68_0
    - libsanitizer 14.3.0 hd08acf3_7
    - libssh2 1.11.1 hcf80075_0
    - libstdcxx 15.2.0 h8f9b012_7
    - libstdcxx-devel_linux-64 14.3.0 h85bb3a7_107
    - libstdcxx-ng 15.2.0 h4852527_7
    - libuv 1.51.0 hb03c661_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - ninja 1.13.1 h171cf75_0
    - openssl 3.5.4 h26f9b46_0
    - rhash 1.4.6 hb9d3cd8_1
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
    - zstd 1.5.7 hb8e6e7a_2
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hda65f42_8
    - c-ares 1.34.5 hb9d3cd8_0
    - c-ares-static 1.34.5 hb9d3cd8_0
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - cli11 2.5.0 h3f2d84a_0
    - cpp-expected 1.3.1 h171cf75_0
    - fmt 11.2.0 h07f6e7f_0
    - keyutils 1.6.3 hb9d3cd8_0
    - krb5 1.21.3 h659f571_0
    - krb5-static 1.21.3 h659f571_0
    - libarchive-minimal-static 3.8.2 lgpl_h0b16566_0
    - libcurl 8.14.1 h332b0f4_0
    - libcurl-static 8.14.1 h332b0f4_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libev-static 4.33 hd590300_2
    - libgcc 15.2.0 h767d61c_7
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - liblzma 5.8.1 hb9d3cd8_2
    - liblzma-devel 5.8.1 hb9d3cd8_2
    - liblzma-static 5.8.1 hbcc6ac9_2
    - libnghttp2 1.67.0 had1ee68_0
    - libnghttp2-static 1.67.0 h5da5774_0
    - libopenssl-static 3.5.4 hb03c661_0
    - libsolv 0.7.35 h9463b59_0
    - libsolv-static 0.7.35 hf0c0ed0_0
    - libssh2 1.11.1 hcf80075_0
    - libssh2-static 1.11.1 hcf80075_0
    - libstdcxx 15.2.0 h8f9b012_7
    - libstdcxx-ng 15.2.0 h4852527_7
    - libzlib 1.3.1 hb9d3cd8_2
    - lz4-c 1.10.0 h5888daf_1
    - lz4-c-static 1.10.0 ha770c72_1
    - ncurses 6.5 h2d0b736_3
    - nlohmann_json 3.12.0 h54a6638_1
    - openssl 3.5.4 h26f9b46_0
    - reproc-cpp-static 14.2.5.post0 h5888daf_0
    - reproc-static 14.2.5.post0 hb9d3cd8_0
    - simdjson 4.0.7 hb700be7_0
    - simdjson-static 4.0.7 hfcd1e18_0
    - spdlog 1.15.3 h6dc744f_1
    - xz-static 5.8.1 hbcc6ac9_2
    - yaml-cpp-static 0.8.0 h3f2d84a_0
    - zlib 1.3.1 hb9d3cd8_2
    - zstd 1.5.7 hb8e6e7a_2
    - zstd-static 1.5.7 h574f1f8_2
  run:
    - __glibc >=2.17,<3.0.a0
test:
  commands:
    - test -f "${PREFIX}/bin/micromamba"
    - test ! -f "${PREFIX}/etc/profile.d/mamba.sh"
    - micromamba --help
    - export MAMBA_ROOT_PREFIX="$(mktemp -d)"
    - micromamba create -n test --override-channels -c conda-forge --yes python=3.9
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" --version'
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" -c "import os"'
about:
  home: https://github.com/mamba-org/mamba
  license_file:
    - CLI11_LICENSE.txt
    - CURL_LICENSE.txt
    - C_ARES_LICENSE.txt
    - FMT_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - LIBEV_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - REPROC_LICENSE.txt
    - SPDLOG_LICENSE.txt
    - TL_EXPECTED_LICENSE.txt
    - ZLIB_LICENSE.txt
    - ZSTD_LICENSE.txt
    - mamba/LICENSE
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/mamba-org/mamba
extra:
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - jjerphan
    - mariusvniekerk
    - pavelzw
    - wolfv
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251017.3.1
  remote_url: https://github.com/conda-forge/micromamba-feedstock
  sha: cce84ed7d6f0f6925ab6e7fb70c18ea280da5ac8
